#!/usr/bin/env bash
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=24

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=kitty

#browser
export BROWSER=chrome
#terminal
export TERM=kitty
#mail
export MAIL=thunderbird

swww-daemon &
swww img ~/Pictures/wp/gbwp2.jpg &
